=== gcronax/xml/OfertasCoches.dtd
<!ELEMENT OfertasCoches (Coche+)>
<!ELEMENT Coche (Marca, Modelo, Matricula, Odometro, PrecioOriginal, PrecioOferta)>
<!ELEMENT Marca (#PCDATA)>
<!ATTLIST Marca paisOrigen CDATA #REQUIRED>
<!ATTLIST Marca rating (1|2|3|4|5) #REQUIRED>
<!ELEMENT Modelo (#PCDATA)>
<!ATTLIST Modelo aÃ±o CDATA #REQUIRED>
<!ATTLIST Modelo version CDATA #IMPLIED>
<!ELEMENT Matricula (#PCDATA)>
<!ATTLIST Matricula paisOrigen CDATA #REQUIRED>
<!ELEMENT Odometro (#PCDATA)>
<!ATTLIST Odometro unidad (km|millas) #REQUIRED>
<!ELEMENT PrecioOriginal (#PCDATA)>
<!ATTLIST PrecioOriginal moneda (euros|dolares|otra) #REQUIRED>
<!ELEMENT PrecioOferta (#PCDATA)>
<!ATTLIST PrecioOferta moneda (euros|dolares|otra) #REQUIRED>

=== gcronax/xml/OfertasCoches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OfertasCoches SYSTEM "OfertasCoches.dtd">
<OfertasCoches>
    <Coche>
        <Marca paisOrigen="japon" rating="5" >Toyota</Marca>
        <Modelo año="2000" version="a">Corolla</Modelo>
        <Matricula paisOrigen="japo">ABC-123</Matricula>
        <Odometro unidad="km"></Odometro>
        <PrecioOriginal moneda="euros">20</PrecioOriginal>
        <PrecioOferta moneda="euros">18</PrecioOferta>
    </Coche>
    <Coche>
        <Marca paisOrigen="japon" rating="5" >Toyota</Marca>
        <Modelo año="2000" >Corolla</Modelo>
        <Matricula paisOrigen="japo">ABC-123</Matricula>
        <Odometro unidad="km"></Odometro>
        <PrecioOriginal moneda="euros">20</PrecioOriginal>
        <PrecioOferta moneda="euros">18</PrecioOferta>
    </Coche>
</OfertasCoches>
